name: Release
on:
  workflow_dispatch:
  push:
    paths:
      - "engorgio/**"
      - "pyproject.toml"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: waylonwalker/hatch-action@v3
        with:
          before-command: "test-lint"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
