name: Release
on:
  workflow_dispatch:
  push:
    paths:
      - "engorgio/**"
      - "pyproject.toml"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: waylonwalker/hatch-action@v2
        with:
          before-command: "test-lint"
